channels:
  - conda-forge
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - affine=2.3.1
  - aiobotocore=2.4.0
  - aiohttp=3.8.3
  - aioitertools=0.11.0
  - aiosignal=1.3.1
  - anyio=3.6.2
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - arrow-cpp=10.0.1
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.27
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.9.379
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - blosc=1.21.2
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - botocore=1.27.59
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - comm=0.1.2
  - contextily=1.2.0
  - contourpy=1.0.6
  - cryptography=38.0.4
  - curl=7.86.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2022.12.0
  - dask-core=2022.12.0
  - debugpy=1.6.4
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.12.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fiona=1.8.22
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - gdal=3.6.1
  - geographiclib=1.52
  - geojson=2.5.0
  - geopy=2.3.0
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.2.1
  - h3-py=3.7.4
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=5.1.0
  - importlib_resources=5.10.1
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.5
  - jupyter_client=7.4.8
  - jupyter_core=5.1.0
  - jupyter_events=0.5.0
  - jupyter_server=2.0.1
  - jupyter_server_terminals=0.4.2
  - jupyterlab=3.5.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.16.5
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - libabseil=20220623.0
  - libarrow=10.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgdal=3.6.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libgoogle-cloud=2.5.0
  - libgrpc=1.51.1
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - locket=1.0.0
  - lz4=4.0.2
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mercantile=1.2.1
  - metis=5.1.0
  - mpfr=4.1.0
  - mpmath=1.2.1
  - msgpack-python=1.0.4
  - multidict=6.0.2
  - munch=2.5.0
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbconvert-core=7.2.6
  - nbconvert-pandoc=7.2.6
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=2.8.8
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.78
  - numpy=1.23.5
  - openjpeg=2.5.0
  - openssl=3.0.7
  - orc=1.8.1
  - packaging=22.0
  - pandas=1.5.2
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - postgresql=15.1
  - proj=9.1.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=10.0.1
  - pycparser=2.21
  - pygments=2.13.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyrsistent=0.19.2
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.6
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qhull=2020.2
  - rasterio=1.3.4
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - rtree=1.0.1
  - s3fs=2022.11.0
  - scikit-learn=1.2.0
  - scikit-mobility=1.3.1
  - scipy=1.9.3
  - send2trash=1.8.0
  - setuptools=65.5.1
  - shapely=2.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - suitesparse=5.10.1
  - tbb=2021.7.0
  - tblib=1.7.0
  - terminado=0.17.1
  - texttable=1.6.7
  - threadpoolctl=3.1.0
  - tiledb=2.13.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022g
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - websocket-client=1.4.2
  - wheel=0.38.4
  - wrapt=1.14.1
  - xerces-c=3.2.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - alabaster==0.7.12
      - appdirs==1.4.4
      - attrs==21.4.0
      - certifi==2022.12.7
      - docutils==0.17.1
      - folium==0.12.1.post1
      - geopandas==0.10.2
      - gitdb==4.0.10
      - gitpython==3.1.29
      - greenlet==2.0.1
      - humanize==4.4.0
      - igraph==0.9.11
      - imagesize==1.4.1
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.2
      - jsonschema==3.2.0
      - jupyter-book==0.13.1
      - jupyter-cache==0.4.3
      - jupyter-events==0.4.0
      - jupyter-server-mathjax==0.2.6
      - jupyter-sphinx==0.3.2
      - jupyterlab-widgets==1.1.1
      - latexcodec==2.0.1
      - linkify-it-py==1.0.3
      - lxml==4.9.2
      - markdown-it-py==1.1.0
      - mdit-py-plugins==0.2.8
      - mistune==0.8.4
      - myst-nb==0.13.2
      - myst-parser==0.15.2
      - nbclient==0.5.13
      - nbconvert==6.5.4
      - nbdime==3.1.1
      - polycircles==0.3.7
      - pooch==1.6.0
      - powerlaw==1.5
      - pybtex==0.24.0
      - pybtex-docutils==1.0.2
      - pydata-sphinx-theme==0.8.1
      - python-igraph==0.9.11
      - python-json-logger==2.0.4
      - smmap==5.0.0
      - snowballstemmer==2.2.0
      - sphinx==4.5.0
      - sphinx-book-theme==0.3.3
      - sphinx-comments==0.0.3
      - sphinx-copybutton==0.5.1
      - sphinx-design==0.1.0
      - sphinx-external-toc==0.2.4
      - sphinx-jupyterbook-latex==0.4.7
      - sphinx-multitoc-numbering==0.1.3
      - sphinx-thebe==0.1.2
      - sphinx-togglebutton==0.3.2
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-bibtex==2.5.0
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - sqlalchemy==1.4.45
      - uc-micro-py==1.0.1
      - webencodings==0.5.1
      - widgetsnbextension==3.6.1
