# Book settings
title:
author: World Bank Development Data Group
logo: docs/images/logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

repository:
    url: https://github.com/datapartnership/syria-economic-monitor
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://datapartnership.github.io/datapartnership/syria-economic-monitor
    extra_footer: |
        <div>
        Country borders or names do not necessarily reflect the World Bank Group’s official position. All maps are for illustrative purposes and do not imply the expression of any opinion on the part of the World Bank, concerning the legal status of any country or territory or concerning the delimitation of frontiers or boundaries
        </div>
        <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://www.mozilla.org/en-US/MPL">Mozilla Public License.</a></b>
        </div>
    google_analytics_id: G-ETJ4QT0E4L

#######################################################################################
# Execution settings
execute:
    execute_notebooks: "off"

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
    - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
    config:
        bibtex_reference_style: author_year
        mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        html_last_updated_fmt: "%b %d, %Y"
        html_show_copyright: false
